# Generated by Django 5.2.2 on 2025-06-14 19:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_system', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='check_in_time',
            field=models.DateTimeField(blank=True, help_text='Čas příchodu do práce', null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='check_out_time',
            field=models.DateTimeField(blank=True, help_text='Čas odchodu z práce', null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='location',
            field=models.CharField(blank=True, help_text='Název budovy nebo pracoviště', max_length=255, null=True),
        ),
        migrations.CreateModel(
            name='EmployeeReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('content', models.TextField(help_text='Obsah reportu')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='app_system.employee')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
    ]
