# Generated by Django 5.2.2 on 2025-06-19 00:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_system', '0003_remove_employee_check_in_time_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Leave',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('leave_type', models.CharField(choices=[('VACATION', 'Dovolená'), ('SICK', 'Nemocenská'), ('PERSONAL', 'Osobní volno'), ('OTHER', 'Jiné')], max_length=20)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('status', models.CharField(choices=[('PENDING', 'Čeká na schválení'), ('APPROVED', 'Schváleno'), ('REJECTED', 'Zamítnuto'), ('CANCELLED', 'Zrušeno')], default='PENDING', max_length=20)),
                ('reason', models.TextField(blank=True, null=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app_system.employee')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leaves', to='app_system.employee')),
            ],
        ),
    ]
