# Generated by Django 5.2.2 on 2025-06-22 20:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_system', '0006_employee_user_alter_leave_approved_by'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TransactionCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Název kategorie')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Popis kategorie')),
                ('type', models.CharField(choices=[('INCOME', 'Příjem'), ('EXPENSE', 'Výdaj')], max_length=10, verbose_name='Typ (Příjem/Výdaj)')),
            ],
            options={
                'verbose_name': 'Kategorie Transakce',
                'verbose_name_plural': 'Kategorie Transakcí',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Název transakce')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Popis')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Částka')),
                ('type', models.CharField(choices=[('INCOME', 'Příjem'), ('EXPENSE', 'Výdaj')], max_length=10, verbose_name='Typ transakce')),
                ('payment_method', models.CharField(choices=[('CASH', 'Hotovost'), ('BANK_TRANSFER', 'Bankovní převod'), ('CARD', 'Platební karta'), ('OTHER', 'Jiné')], default='BANK_TRANSFER', max_length=20, verbose_name='Způsob platby')),
                ('transaction_date', models.DateField(verbose_name='Datum transakce')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Vytvořeno')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Aktualizováno')),
                ('party_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Strana transakce (Klient/Dodavatel)')),
                ('recorded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recorded_transactions', to=settings.AUTH_USER_MODEL, verbose_name='Zaznamenal(a)')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='app_system.transactioncategory', verbose_name='Kategorie')),
            ],
            options={
                'verbose_name': 'Transakce',
                'verbose_name_plural': 'Transakce',
                'ordering': ['-transaction_date', '-created_at'],
            },
        ),
    ]
